version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "nuget"
    directory: "/src.csharp"
    schedule:
      interval: "weekly"
            
  - package-ecosystem: "gradle"
    directory: "/src.kotlin/alphaTab"
    schedule:
      interval: "weekly"
